apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox 
spec:
  ports:
  - port: 411
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
  type: ClusterIP