apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-techtrends-prod.yaml
  name: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm
    repoURL: https://github.com/nulladams/nd064_course_1
    targetRevision: HEAD